/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACascader: typeof import('ant-design-vue/es')['Cascader']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATimePicker: typeof import('ant-design-vue/es')['TimePicker']
    ATimeRangePicker: typeof import('ant-design-vue/es')['TimeRangePicker']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    DataTimeRangePicker: typeof import('./src/components/zjwComp/dataTimeRangePicker/index.vue')['default']
    DateTimeRangePicker: typeof import('./src/components/zjwComp/dateTimeRangePicker/index.vue')['default']
    Table: typeof import('./src/components/zjwComp/table/index.vue')['default']
    TableButton: typeof import('./src/components/zjwComp/table/tableButton/index.vue')['default']
    TableSearch: typeof import('./src/components/zjwComp/table/tableSearch/index.vue')['default']
    TestComponent: typeof import('./src/components/testComponent/index.vue')['default']
    TimeRangePicker: typeof import('./src/components/zjwComp/timeRangePicker/index.vue')['default']
  }
}
